name: Update Fear & Greed CSV

# <- assure-toi qu'il n'y a PAS d'espaces avant "on:"
on:
  # déclenchement programmé chaque jour à 01:00 UTC
  schedule:
    - cron: '0 1 * * *'
  # permet aussi de lancer manuellement depuis l'UI Actions
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Installer curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Rendre le script exécutable
        run: chmod +x update_fng.sh

      - name: Fetch and commit FNG CSV
        run: ./update_fng.sh
